/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes.index'
import { Route as ExamsIndexRouteImport } from './routes/exams.index'
import { Route as DepartmentsIndexRouteImport } from './routes/departments.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects.$subjectId'
import { Route as QuizzesQuizIdRouteImport } from './routes/quizzes.$quizId'
import { Route as ExamsExamIdRouteImport } from './routes/exams.$examId'
import { Route as DepartmentsDeptIdRouteImport } from './routes/departments.$deptId'
import { Route as DashboardScheduleRouteImport } from './routes/dashboard.schedule'
import { Route as DashboardRoadmapRouteImport } from './routes/dashboard.roadmap'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardGradesRouteImport } from './routes/dashboard.grades'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard.assignments'
import { Route as DashboardAchievementsRouteImport } from './routes/dashboard.achievements'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminInstructorsRouteImport } from './routes/admin.instructors'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as SubjectsRouteImport } from './routes/subjects.'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdRoute = QuizzesQuizIdRouteImport.update({
  id: '/quizzes/$quizId',
  path: '/quizzes/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdRoute = ExamsExamIdRouteImport.update({
  id: '/exams/$examId',
  path: '/exams/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsDeptIdRoute = DepartmentsDeptIdRouteImport.update({
  id: '/departments/$deptId',
  path: '/departments/$deptId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardScheduleRoute = DashboardScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoadmapRoute = DashboardRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGradesRoute = DashboardGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAchievementsRoute = DashboardAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstructorsRoute = AdminInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/subjects/': typeof SubjectsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/grades': typeof DashboardGradesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/departments/$deptId': typeof DepartmentsDeptIdRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/subjects': typeof SubjectsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/grades': typeof DashboardGradesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/departments/$deptId': typeof DepartmentsDeptIdRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/departments': typeof DepartmentsIndexRoute
  '/exams': typeof ExamsIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/subjects/': typeof SubjectsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/grades': typeof DashboardGradesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/departments/$deptId': typeof DepartmentsDeptIdRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/books'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/live'
    | '/login'
    | '/signup'
    | '/subjects/'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/finance'
    | '/admin/instructors'
    | '/admin/permissions'
    | '/admin/settings'
    | '/admin/subjects'
    | '/admin/users'
    | '/courses/$courseId'
    | '/dashboard/achievements'
    | '/dashboard/assignments'
    | '/dashboard/courses'
    | '/dashboard/grades'
    | '/dashboard/profile'
    | '/dashboard/roadmap'
    | '/dashboard/schedule'
    | '/departments/$deptId'
    | '/exams/$examId'
    | '/quizzes/$quizId'
    | '/subjects/$subjectId'
    | '/admin/'
    | '/courses/'
    | '/dashboard/'
    | '/departments/'
    | '/exams/'
    | '/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/books'
    | '/contact'
    | '/live'
    | '/login'
    | '/signup'
    | '/subjects'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/finance'
    | '/admin/instructors'
    | '/admin/permissions'
    | '/admin/settings'
    | '/admin/subjects'
    | '/admin/users'
    | '/courses/$courseId'
    | '/dashboard/achievements'
    | '/dashboard/assignments'
    | '/dashboard/courses'
    | '/dashboard/grades'
    | '/dashboard/profile'
    | '/dashboard/roadmap'
    | '/dashboard/schedule'
    | '/departments/$deptId'
    | '/exams/$examId'
    | '/quizzes/$quizId'
    | '/subjects/$subjectId'
    | '/admin'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/exams'
    | '/quizzes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/books'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/live'
    | '/login'
    | '/signup'
    | '/subjects/'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/finance'
    | '/admin/instructors'
    | '/admin/permissions'
    | '/admin/settings'
    | '/admin/subjects'
    | '/admin/users'
    | '/courses/$courseId'
    | '/dashboard/achievements'
    | '/dashboard/assignments'
    | '/dashboard/courses'
    | '/dashboard/grades'
    | '/dashboard/profile'
    | '/dashboard/roadmap'
    | '/dashboard/schedule'
    | '/departments/$deptId'
    | '/exams/$examId'
    | '/quizzes/$quizId'
    | '/subjects/$subjectId'
    | '/admin/'
    | '/courses/'
    | '/dashboard/'
    | '/departments/'
    | '/exams/'
    | '/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  BooksRoute: typeof BooksRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SubjectsRoute: typeof SubjectsRoute
  DepartmentsDeptIdRoute: typeof DepartmentsDeptIdRoute
  ExamsExamIdRoute: typeof ExamsExamIdRoute
  QuizzesQuizIdRoute: typeof QuizzesQuizIdRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId': {
      id: '/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof QuizzesQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId': {
      id: '/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof ExamsExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$deptId': {
      id: '/departments/$deptId'
      path: '/departments/$deptId'
      fullPath: '/departments/$deptId'
      preLoaderRoute: typeof DepartmentsDeptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/schedule': {
      id: '/dashboard/schedule'
      path: '/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof DashboardScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roadmap': {
      id: '/dashboard/roadmap'
      path: '/roadmap'
      fullPath: '/dashboard/roadmap'
      preLoaderRoute: typeof DashboardRoadmapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/grades': {
      id: '/dashboard/grades'
      path: '/grades'
      fullPath: '/dashboard/grades'
      preLoaderRoute: typeof DashboardGradesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/achievements': {
      id: '/dashboard/achievements'
      path: '/achievements'
      fullPath: '/dashboard/achievements'
      preLoaderRoute: typeof DashboardAchievementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instructors': {
      id: '/admin/instructors'
      path: '/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AdminInstructorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminInstructorsRoute: typeof AdminInstructorsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminInstructorsRoute: AdminInstructorsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface DashboardRouteChildren {
  DashboardAchievementsRoute: typeof DashboardAchievementsRoute
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRoute
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardGradesRoute: typeof DashboardGradesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRoadmapRoute: typeof DashboardRoadmapRoute
  DashboardScheduleRoute: typeof DashboardScheduleRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAchievementsRoute: DashboardAchievementsRoute,
  DashboardAssignmentsRoute: DashboardAssignmentsRoute,
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardGradesRoute: DashboardGradesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRoadmapRoute: DashboardRoadmapRoute,
  DashboardScheduleRoute: DashboardScheduleRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  BooksRoute: BooksRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SubjectsRoute: SubjectsRoute,
  DepartmentsDeptIdRoute: DepartmentsDeptIdRoute,
  ExamsExamIdRoute: ExamsExamIdRoute,
  QuizzesQuizIdRoute: QuizzesQuizIdRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
